name: coding_challenge_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image: ^4.2.0
  dio: ^5.7.0
  intl: ^0.19.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.8
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true
  generate: true

assets:
  - assets/